/**
 * @author reinoud
 */
class Config {
	static var GLOBAL_LOGLEVEL:LuminicBox.Log.Level = LuminicBox.Log.Level.INFO
	
	static var GETDIR_SERVER_URL:String = "http://"+_root.SERVER+"/getdir/";
	static var RTMP_SERVER_URL:String = "rtmp://"+_root.SERVER;
	static var RTMP_TESTFLV:String = "simps-0000";
	
	static var APPLICATION_DRAGGING_SCREENWIDTH_TIME_SECONDS:Number=600

	static var TITLEBAR_FONTSIZE:Number=30;
	static var TITLEBAR_FONTCOLOR:Number=0xdfdfff;
	static var TITLEBAR_PADDING:Number=15;
	static var TITLEBAR_TIMEOUT:Number=5000;
	static var TITLEBAR_MAX_ALPHA:Number=80;
	static var TITLEBAR_APPEAR_SPEED:Number=10;
	static var TITLEBAR_DISAPPEAR_SPEED:Number=5;

	static var TITLEBAR_TOP_X:Number=0
	static var TITLEBAR_TOP_Y:Number=0
	static var TITLEBAR_TOP_WIDTH:Number=Stage.width
	static var TITLEBAR_TOP_HEIGHT:Number=Config.TITLEBAR_PADDING*3+Config.TITLEBAR_FONTSIZE*3;
	
	static var TITLEBAR_FILESELECTOR_BUTTON_WIDTH:Number=50;
	static var TITLEBAR_FILESELECTOR_BUTTON_HEIGHT:Number=30;
	static var TITLEBAR_FILESELECTOR_X:Number=Stage.width-Config.TITLEBAR_FILESELECTOR_BUTTON_WIDTH*.5-Config.TITLEBAR_PADDING;
	static var TITLEBAR_FILESELECTOR_Y:Number=Config.TITLEBAR_PADDING+Config.TITLEBAR_FILESELECTOR_BUTTON_HEIGHT*.5;

	static var TITLEBAR_PAUSE_BUTTON_WIDTH:Number=50;
	static var TITLEBAR_PAUSE_BUTTON_HEIGHT:Number=30;
	static var TITLEBAR_PAUSE_X:Number=Stage.width-Config.TITLEBAR_FILESELECTOR_BUTTON_WIDTH*1.5-2*Config.TITLEBAR_PADDING;
	static var TITLEBAR_PAUSE_Y:Number=Config.TITLEBAR_PADDING+Config.TITLEBAR_FILESELECTOR_BUTTON_HEIGHT*.5;

	static var TITLEBAR_PLAYLIST_BUTTON_WIDTH:Number=50;
	static var TITLEBAR_PLAYLIST_BUTTON_HEIGHT:Number=30;
	static var TITLEBAR_PLAYLIST_X:Number=Stage.width-Config.TITLEBAR_FILESELECTOR_BUTTON_WIDTH*2.5-3*Config.TITLEBAR_PADDING;
	static var TITLEBAR_PLAYLIST_Y:Number=Config.TITLEBAR_PADDING+Config.TITLEBAR_FILESELECTOR_BUTTON_HEIGHT*.5;
	
	static var TITLEBAR_TITLE_X:Number=Config.TITLEBAR_PADDING;
	static var TITLEBAR_TITLE_Y:Number=0;
	static var TITLEBAR_TITLE_WIDTH:Number=Stage.width;
	static var TITLEBAR_TITLE_HEIGHT:Number=Config.TITLEBAR_FONTSIZE;
	
	static var TITLEBAR_TIME_X:Number=Config.TITLEBAR_PADDING;
	static var TITLEBAR_TIME_Y:Number= TITLEBAR_FONTSIZE + Config.TITLEBAR_PADDING;
	static var TITLEBAR_TIME_WIDTH:Number=300;
	static var TITLEBAR_TIME_HEIGHT:Number=Config.TITLEBAR_FONTSIZE;
	
	static var TITLEBAR_FPS_X:Number=Config.TITLEBAR_PADDING*2+Config.TITLEBAR_TIME_WIDTH;
	static var TITLEBAR_FPS_Y:Number= TITLEBAR_FONTSIZE + Config.TITLEBAR_PADDING;
	static var TITLEBAR_FPS_WIDTH:Number=Config.TITLEBAR_TIME_X+Config.TITLEBAR_TIME_WIDTH+Config.TITLEBAR_PADDING;
	static var TITLEBAR_FPS_HEIGHT:Number=Config.TITLEBAR_FONTSIZE;
	
	
	static var WIIBUTTON_MAXSCALE:Number=170;
	static var WIIBUTTON_SCALE_SPEED:Number=30;

	static var WIIBUTTON_ENABLED_FONTSIZE:Number=15;
	static var WIIBUTTON_ENABLED_FONTCOLOR:Number=0x000000;
	static var WIIBUTTON_DISABLED_FONTSIZE:Number=15;
	static var WIIBUTTON_DISABLED_FONTCOLOR:Number=0x7F7F7F;
	static var WIIBUTTON_PADDING:Number=3;
	static var WIIBUTTON_FLASHINTERNAL_TEXTFIELD_PADDING:Number=Config.WIIBUTTON_ENABLED_FONTSIZE*.15;
	
	static var FILESELECTOR_EXTERNALPADDING:Number = 10
	static var FILESELECTOR_X:Number = Config.FILESELECTOR_EXTERNALPADDING
	static var FILESELECTOR_Y:Number = Config.FILESELECTOR_EXTERNALPADDING
	static var FILESELECTOR_WIDTH:Number = Stage.width-2*Config.FILESELECTOR_EXTERNALPADDING
	static var FILESELECTOR_HEIGHT:Number = Stage.height-2*Config.FILESELECTOR_EXTERNALPADDING
	
	static var FILESELECTOR_PADDING:Number = 5

	static var FILESELECTOR_TITLE_FONTSIZE:Number = 20
	static var FILESELECTOR_TITLE_FONTCOLOR:Number = 0x00007f

	static var FILESELECTOR_NAVBUTTON_WIDTH:Number = 45
	static var FILESELECTOR_NAVBUTTON_HEIGHT:Number = 30
	
	static var FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY:Number = 2
	static var FILESELECTOR_FILEBUTTON_NR_VERTICALLY:Number = 11
	static var FILESELECTOR_FILEBUTTON_WIDTH:Number = (Config.FILESELECTOR_WIDTH-Config.FILESELECTOR_PADDING*(Config.FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY+1))/Config.FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY
	static var FILESELECTOR_FILEBUTTON_HEIGHT:Number = 30
	
	static var FILESELECTOR_HEADER_HEIGHT:Number = Config.FILESELECTOR_HEIGHT - (Config.FILESELECTOR_FILEBUTTON_HEIGHT*Config.FILESELECTOR_FILEBUTTON_NR_VERTICALLY+(Config.FILESELECTOR_PADDING*(Config.FILESELECTOR_FILEBUTTON_NR_VERTICALLY+1)))
	
	static var DRAGGER_SENSIBILITY:Number=Math.pow(25,2); // regard any movement smaller that sqrt(this number) during mousedown not as dragging
	
	static var PLAYLIST_BGCOLOR:Number = 0x3333FF
	static var PLAYLIST_X:Number = 0
	static var PLAYLIST_Y:Number = 0
	static var PLAYLIST_WIDTH:Number = Stage.width/3
	static var PLAYLIST_HEIGHT:Number = Stage.height
	static var PLAYLIST_ENTRYHEIGHT:Number = 25
	static var PLAYLIST_PADDING:Number = 5
	
	static var PLAYLIST_LIST_BGCOLOR:Number = 0x4444FF
	static var PLAYLIST_LIST_Y:Number = 40
	static var PLAYLIST_LIST_WIDTH:Number = Config.PLAYLIST_WIDTH
	static var PLAYLIST_LIST_HEIGHT:Number = Config.PLAYLIST_HEIGHT-Config.PLAYLIST_LIST_Y*2
	
	static var PLAYLISTENTRY_FONTSIZE:Number = 20
	static var PLAYLISTENTRY_FONTCOLOR_INACTIVE:Number = 0xdfdfff
	static var PLAYLISTENTRY_FONTCOLOR_ACTIVE:Number = 0xffff7f
	
}