/**
 * @author reinoud
 */
class Config {
	static var GLOBAL_LOGLEVEL:LuminicBox.Log.Level = LuminicBox.Log.Level.INFO
	
	static var GETDIR_SERVER_URL:String = "http://10.1.0.20/getdir/";
	static var RTMP_SERVER_URL:String = "rtmp://10.1.0.20";
	static var RTMP_TESTFLV:String = "simps-0000";

	static var TITLEBAR_FONTSIZE:Number=30;
	static var TITLEBAR_FONTCOLOR:Number=0xdfdfff;
	static var TITLEBAR_PADDING:Number=15;
	static var TITLEBAR_TIMEOUT:Number=5000;
	static var TITLEBAR_MAX_ALPHA:Number=80;
	static var TITLEBAR_APPEAR_SPEED:Number=10;
	static var TITLEBAR_DISAPPEAR_SPEED:Number=5;
	
	static var WIIBUTTON_MAXSCALE:Number=170;
	static var WIIBUTTON_SCALE_SPEED:Number=30;

	static var WIIBUTTON_FONTSIZE:Number=15;
	static var WIIBUTTON_FLASHINTERNAL_TEXTFIELD_PADDING:Number=Config.WIIBUTTON_FONTSIZE*.15;
	static var WIIBUTTON_FONTCOLOR:Number=0x000000;
	static var WIIBUTTON_PADDING:Number=3;
	
	static var FILESELECTOR_X:Number = 50
	static var FILESELECTOR_Y:Number = 50
	static var FILESELECTOR_WIDTH:Number = Stage.width-2*Config.FILESELECTOR_X
	static var FILESELECTOR_HEIGHT:Number = Stage.height-Config.FILESELECTOR_Y
	
	static var FILESELECTOR_PADDING:Number = 5

	static var FILESELECTOR_TITLE_FONTSIZE:Number = 20
	static var FILESELECTOR_TITLE_FONTCOLOR:Number = 0x00007f

	static var FILESELECTOR_NAVBUTTON_WIDTH:Number = 45
	static var FILESELECTOR_NAVBUTTON_HEIGHT:Number = 30
	
	static var FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY:Number = 3
	static var FILESELECTOR_FILEBUTTON_NR_VERTICALLY:Number = 10
	static var FILESELECTOR_FILEBUTTON_WIDTH:Number = (Config.FILESELECTOR_WIDTH-Config.FILESELECTOR_PADDING*(Config.FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY+1))/Config.FILESELECTOR_FILEBUTTON_NR_HORIZONTALLY
	static var FILESELECTOR_FILEBUTTON_HEIGHT:Number = 30
	
	static var FILESELECTOR_HEADER_HEIGHT:Number = Config.FILESELECTOR_HEIGHT - (Config.FILESELECTOR_FILEBUTTON_HEIGHT*Config.FILESELECTOR_FILEBUTTON_NR_VERTICALLY+(Config.FILESELECTOR_PADDING*(Config.FILESELECTOR_FILEBUTTON_NR_VERTICALLY+1)))
}